export default {
  EDIT_ADDRESS: 'EDIT_ADDRESS',

  EDIT_FOOD_CATEGORY_LIST: 'EDIT_FOOD_CATEGORY_LIST',

  EDIT_NEARBY_MERCHANT_LIST: 'EDIT_NEARBY_MERCHANT_LIST',
  EDIT_MERCHANT_INFO: 'EDIT_MERCHANT_INFO',
  EDIT_MERCHANT_FOOD_LIST: 'EDIT_MERCHANT_FOOD_LIST',
  EDIT_MERCHANT_RATING_LIST: 'EDIT_MERCHANT_RATINGS_LIST',

  EDIT_USER_INFO: 'EDIT_USER_INFO'
};
